version: '3.4'

services:
  app:
    image: rmly/ping-trace:latest
    restart: always
    command: npm run prod
    environment:
      - NPM_CONFIG_CACHE=/usr/src/app/.npm-cache
      - HOST=0.0.0.0
      - PORT=5989
    networks:
      - ping-trace
    ports:
      - 5989:5989

networks:
  ping-trace:
    name: ping-trace
    driver: bridge
